import './globals.css';
import SupabaseProvider from './supabase-provider';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <Navbar />
          <main>{children}</main>
        </SupabaseProvider>
      </body>
    </html>
  );
}
